name: "\U0001F9EA Lab Request"
description: Request a new WTSG / ASVS Lab to be added
title: "\U0001F9EA LAB REQUEST:"
labels: []
assignees: []
body:
  - type: input
    id: identifier
    attributes:
      label: Identifier
      description: Is this Lab reference a particular specification? (Currently, we're only focusing on WTSG / ASVS)
      placeholder: WSTG-SESS-01
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      description: What is the name of the Lab?
      placeholder: Testing for Session Management Schema
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is this Lab trying to demonostrate?
      placeholder: In this Lab, we'll be testing for secure Session Management Schema because...
    validations:
      required: true
  - type: dropdown
    id: langages
    attributes:
      label: Language(s)
      multiple: true
      options:
        - Python
        - JS
        - Java
        - C
  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      description: How difficult do you think this Lab is to implement?
      options:
        - Easy
        - Medium
        - Hard
